use crate::language::Language;
use crate::parser::ParsedData;
use crate::rust_types::RustConstExpr;
use crate::rust_types::RustTypeFormatError;
use crate::rust_types::SpecialRustType;
use crate::RenameExt;
use std::collections::BTreeSet;
use std::collections::HashMap;
use std::io::Write;

#[derive(Default)]
pub struct Cpp {
    /// std library headers
    pub imports: BTreeSet<String>,
    pub type_mappings: HashMap<String, String>,
}

impl Language for Cpp {
    fn generate_types(
        &mut self,
        w: &mut dyn Write,
        _imports: &super::CrateTypes,
        data: ParsedData,
    ) -> std::io::Result<()> {
        self.begin_file(w, &data)?;

        let ParsedData {
            structs,
            enums,
            aliases,
            consts,
            ..
        } = data;

        let mut body: Vec<u8> = Vec::new();

        for a in aliases {
            self.write_type_alias(&mut body, &a)?;
        }

        for c in consts {
            self.write_const(&mut body, &c)?;
        }

        for e in enums {
            // TODO - implement enum generation
            self.write_enum(&mut body, &e)?;
        }

        for s in structs {
            self.write_struct(&mut body, &s)?;
            writeln!(&mut body)?;
        }

        self.write_all_imports(w)?;
        w.write_all(&body)?;
        self.end_file(w)
    }

    fn type_map(&mut self) -> &HashMap<String, String> {
        &self.type_mappings
    }

    // TODO - add all imports + initialise where appropriate
    fn format_special_type(
        &mut self,
        special_ty: &SpecialRustType,
        generic_types: &[String],
    ) -> Result<String, RustTypeFormatError> {
        Ok(match special_ty {
            SpecialRustType::Vec(rtype) => {
                self.add_import("vector");
                format!("std::vector<{}>", self.format_type(rtype, generic_types)?)
            }
            SpecialRustType::Array(rtype, len) => {
                format!(
                    "std::array<{}, {}>",
                    self.format_type(rtype, generic_types)?,
                    len
                )
            }
            SpecialRustType::Slice(rtype) => {
                format!("std::vector<{}>", self.format_type(rtype, generic_types)?)
            }
            SpecialRustType::Option(rtype) => {
                format!("std::optional<{}>", self.format_type(rtype, generic_types)?)
            }
            SpecialRustType::HashMap(rtype1, rtype2) => format!(
                "std::unordered_map<{}, {}>",
                self.format_type(rtype1, generic_types)?,
                self.format_type(rtype2, generic_types)?
            ),
            SpecialRustType::Unit => "void".into(),
            SpecialRustType::String => "std::string".into(),
            SpecialRustType::Char => "char".into(),
            SpecialRustType::I8 => {
                self.add_import("cstdint");
                "int8_t".into()
            }
            SpecialRustType::U8 => {
                self.add_import("cstdint");
                "uint8_t".into()
            }
            SpecialRustType::I16 => {
                self.add_import("cstdint");
                "int16_t".into()
            }
            SpecialRustType::U16 => {
                self.add_import("cstdint");
                "uint16_t".into()
            }
            SpecialRustType::I32 => {
                self.add_import("cstdint");
                "int32_t".into()
            }
            SpecialRustType::U32 => {
                self.add_import("cstdint");
                "uint32_t".into()
            }
            SpecialRustType::I54 | SpecialRustType::I64 => {
                self.add_import("cstdint");
                "int64_t".into()
            }
            SpecialRustType::U53 | SpecialRustType::U64 => {
                self.add_import("cstdint");
                "uint64_t".into()
            }
            SpecialRustType::ISize => {
                self.add_import("cstdint");
                "intptr_t".into()
            }
            SpecialRustType::USize => {
                self.add_import("cstdint");
                "uintptr_t".into()
            }
            SpecialRustType::Bool => "bool".into(),
            SpecialRustType::F32 => "float".into(),
            SpecialRustType::F64 => "double".into(),
            SpecialRustType::DateTime => {
                // TODO
                return Err(RustTypeFormatError::UnsupportedSpecialType(
                    special_ty.to_string(),
                ));
            }
        })
    }

    fn begin_file(&mut self, w: &mut dyn Write, _parsed_data: &ParsedData) -> std::io::Result<()> {
        writeln!(w, "// This code is generated by typeshare")?;
        Ok(())
    }

    fn write_imports(
        &mut self,
        _writer: &mut dyn Write,
        _imports: super::ScopedCrateTypes<'_>,
    ) -> std::io::Result<()> {
        Ok(())
    }

    fn write_struct(
        &mut self,
        w: &mut dyn Write,
        rs: &crate::rust_types::RustStruct,
    ) -> std::io::Result<()> {
        writeln!(w, "struct {} {{", rs.id.original)?;

        for field in &rs.fields {
            let type_name = self.format_type(&field.ty, &[]).unwrap();
            writeln!(w, "    {} {};", type_name, field.id.original)?;
        }

        writeln!(w, "}};")?;
        Ok(())
    }

    fn write_type_alias(
        &mut self,
        w: &mut dyn Write,
        ta: &crate::rust_types::RustTypeAlias,
    ) -> std::io::Result<()> {
        let type_name = self.format_type(&ta.r#type, &[]).unwrap();
        writeln!(w, "using {} = {};", ta.id.original, type_name)?;
        Ok(())
    }

    fn write_const(
        &mut self,
        w: &mut dyn Write,
        c: &crate::rust_types::RustConst,
    ) -> std::io::Result<()> {
        match c.expr {
            RustConstExpr::Int(val) => {
                let const_type = self
                    .format_type(&c.r#type, &[])
                    .map_err(std::io::Error::other)?;
                writeln!(
                    w,
                    "constexpr {} {} = {};",
                    const_type,
                    c.id.renamed.to_snake_case().to_uppercase(),
                    val
                )
            }
        }
    }
}

impl Cpp {
    fn add_import(&mut self, name: &str) {
        self.imports.insert(name.to_string());
    }

    fn write_all_imports(&self, w: &mut dyn Write) -> std::io::Result<()> {
        let mut imports = self.imports.iter().cloned().collect::<Vec<String>>();
        imports.sort();
        match imports.as_slice() {
            [] => return Ok(()),
            _ => {
                for import in imports {
                    writeln!(w, "#include <{import}>")?;
                }
            }
        }
        writeln!(w)
    }
}
