// This code is generated by typeshare
#include <cstdint>
#include <vector>

struct Location {
};

struct Person {
    std::string name;
    uint8_t age;
    std::optional<std::string> info;
    std::vector<std::string> emails;
    Location location;
};

